---
- hosts: ubuntu
  become: yes

  tasks:

  - name: Sistema actualizado
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true
    notify: Reiniciar sistema

  - name: No permitir login como root
    ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       insertafter: '^#PermitRootLogin'
       line: PermitRootLogin no
    notify: Reiniciar daemon ssh
 
  - name: Existe directorio /opt/test
    ansible.builtin.file:
      path: /opt/test
      state: directory
      owner: nobody
      group: nogroup
      mode: '0777'
    register: resultado

  - name: Mostrar resultado
    ansible.builtin.debug:
      msg: "{{ resultado.diff.after  }}"
    when: resultado.changed

  handlers:

  - name: Reiniciar sistema
    ansible.builtin.reboot:

  - name: Reiniciar daemon ssh
    ansible.builtin.systemd_service:
      name: sshd
      state: restarted
