---
- name: Play para la instalacion y configuracion inicial de webserver
  hosts: webserver
  become: yes

  tasks:
  
  - name: El paquete httpd tiene que estar instalado
    ansible.builtin.dnf:
      name: "{{ paquete }}"
      state: present 

  - name: El servicio httpd iniciado y habilitado
    ansible.builtin.systemd_service:
      name: "{{ service  }}"
      enabled: true
      state: started
  
  - name: Puertos habilitados en el firewall
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop: "{{ servicio_firewall  }}"      

  - name: Archivo indice customizado
    ansible.builtin.template:
      src: ../templates/index.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: u=rw,g=r,o=r
 
